In [1]:
import numpy as np
import pandas as pd

In [70]:
df=pd.read_csv('titanic.csv')
df.head()

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
0,0,3,male,22.0,1,0,7.2500,S,NaN
1,1,1,female,38.0,1,0,71.2833,C,C
2,1,3,female,26.0,0,0,7.9250,S,NaN
3,1,1,female,35.0,1,0,53.1000,S,C
4,0,3,male,35.0,0,0,8.0500,S,NaN


1. Display:
   - first 10 rows
   - last 10 rows
   - dataset shape
   - column names

In [8]:
#first 10 rows
df.head(10)

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
0,0,3,male,22.0,1,0,7.2500,S,NaN
1,1,1,female,38.0,1,0,71.2833,C,C
2,1,3,female,26.0,0,0,7.9250,S,NaN
3,1,1,female,35.0,1,0,53.1000,S,C
4,0,3,male,35.0,0,0,8.0500,S,NaN
5,0,3,male,NaN,0,0,8.4583,Q,NaN
6,0,1,male,54.0,0,0,51.8625,S,E
7,0,3,male,2.0,3,1,21.0750,S,NaN
8,1,3,female,27.0,0,2,11.1333,S,NaN
9,1,2,female,14.0,1,0,30.0708,C,NaN


In [5]:
df.tail(10)

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
881,0,3,male,33.0,0,0,7.8958,S,NaN
882,0,3,female,22.0,0,0,10.5167,S,NaN
883,0,2,male,28.0,0,0,10.5000,S,NaN
884,0,3,male,25.0,0,0,7.0500,S,NaN
885,0,3,female,39.0,0,5,29.1250,Q,NaN
886,0,2,male,27.0,0,0,13.0000,S,NaN
887,1,1,female,19.0,0,0,30.0000,S,B
888,0,3,female,NaN,1,2,23.4500,S,NaN
889,1,1,male,26.0,0,0,30.0000,C,C
890,0,3,male,32.0,0,0,7.7500,Q,NaN


In [9]:
# dataset shape
df.shape

(891, 9)

In [7]:
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

2. find
   - total number of passengers
   - number of male passengers
   - number of female passengers

In [35]:
# total number of passengers
df.shape[0]

891

In [13]:
df['gender'].value_counts()

gender
male      577
female    314
Name: count, dtype: int64

3. Display
   - data tpes of all columns
   - number of missing values in each column

In [23]:
df.dtypes

survived      int64
pclass        int64
gender       object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
deck         object
dtype: object

In [24]:
df.isnull().sum()

survived      0
pclass        0
gender        0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

4. find
   - minimum age
   - maximum age
   - average age
   - median age


In [26]:
df['age'].min()

0.42

In [27]:
df['age'].max()

80.0

In [30]:
print(df['age'].mean())

29.69911764705882


In [31]:
print(df['age'].median())

28.0


5. Display all passengers:
   - whose age is greater than 60

In [36]:
df[ df['age'] >60 ].head()  #whose age is greater than 60

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
33,0,2,male,66.0,0,0,10.5000,S,NaN
54,0,1,male,65.0,0,1,61.9792,C,B
96,0,1,male,71.0,0,0,34.6542,C,A
116,0,3,male,70.5,0,0,7.7500,Q,NaN
170,0,1,male,61.0,0,0,33.5000,S,B


6. Display all female passengers
   - travelling in first class

In [38]:
df[ (df['gender']=='female') & (df['pclass'] ==1) ]

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
1,1,1,female,38.0,1,0,71.2833,C,C
3,1,1,female,35.0,1,0,53.1000,S,C
11,1,1,female,58.0,0,0,26.5500,S,C
31,1,1,female,NaN,1,0,146.5208,C,B
52,1,1,female,49.0,1,0,76.7292,C,D
...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,NaN
862,1,1,female,48.0,0,0,25.9292,S,D
871,1,1,female,47.0,1,1,52.5542,S,D
879,1,1,female,56.0,0,1,83.1583,C,C


7. Display passengers:
   - who survived
   - and whose fare was greater than 50

In [41]:
df[ (df['survived'] == 1) & (df['fare'] > 50) ]

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
1,1,1,female,38.0,1,0,71.2833,C,C
3,1,1,female,35.0,1,0,53.1000,S,C
31,1,1,female,NaN,1,0,146.5208,C,B
52,1,1,female,49.0,1,0,76.7292,C,D
61,1,1,female,38.0,0,0,80.0000,NaN,B
...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,NaN
849,1,1,female,NaN,1,0,89.1042,C,C
856,1,1,female,45.0,1,1,164.8667,S,NaN
871,1,1,female,47.0,1,1,52.5542,S,D


8. Display:
   - passenger name, age, fare
   - for passengers embarked from 'C'

In [111]:
df_8=df[ df['embarked']=='C' ]
df_8.loc[[],['age','fare']]

,age,fare


9. display passengers
    - whose age is between 20 and 30
    - and who did not survive

In [54]:
df[ ( df['age'].between(20,30) ) & (df['survived']==0) ]

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
0,0,3,male,22.0,1,0,7.2500,S,NaN
12,0,3,male,20.0,0,0,8.0500,S,NaN
34,0,1,male,28.0,1,0,82.1708,C,NaN
37,0,3,male,21.0,0,0,8.0500,S,NaN
41,0,2,female,27.0,1,0,21.0000,S,NaN
...,...,...,...,...,...,...,...,...,...
876,0,3,male,20.0,0,0,9.8458,S,NaN
882,0,3,female,22.0,0,0,10.5167,S,NaN
883,0,2,male,28.0,0,0,10.5000,S,NaN
884,0,3,male,25.0,0,0,7.0500,S,NaN


10. top 5 passengers with highest fare

In [55]:
df.nlargest(5,'fare')

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
258,1,1,female,35.0,0,0,512.3292,C,NaN
679,1,1,male,36.0,0,1,512.3292,C,B
737,1,1,male,35.0,0,0,512.3292,C,B
27,0,1,male,19.0,3,2,263.0000,S,C
88,1,1,female,23.0,3,2,263.0000,S,C


In [58]:
df.sort_values(by='fare',ascending=False).head(5)

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
258,1,1,female,35.0,0,0,512.3292,C,NaN
737,1,1,male,35.0,0,0,512.3292,C,B
679,1,1,male,36.0,0,1,512.3292,C,B
88,1,1,female,23.0,3,2,263.0000,S,C
27,0,1,male,19.0,3,2,263.0000,S,C


11. Display
    - youngest 5 passengers

In [56]:
df.nsmallest(5,'age')

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
803,1,3,male,0.42,0,1,8.5167,C,NaN
755,1,2,male,0.67,1,1,14.5000,S,NaN
469,1,3,female,0.75,2,1,19.2583,C,NaN
644,1,3,female,0.75,2,1,19.2583,C,NaN
78,1,2,male,0.83,0,2,29.0000,S,NaN


In [57]:
youngest_5 = df.sort_values(by='age').head()
youngest_5

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck
803,1,3,male,0.42,0,1,8.5167,C,NaN
755,1,2,male,0.67,1,1,14.5000,S,NaN
644,1,3,female,0.75,2,1,19.2583,C,NaN
469,1,3,female,0.75,2,1,19.2583,C,NaN
78,1,2,male,0.83,0,2,29.0000,S,NaN


12. find:
    - average fare for each passenger class(use groupby)

In [73]:
df.groupby('pclass')['fare'].mean()

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

13. find
    - survival count for each gender

In [75]:
df[['gender','survived']].value_counts()

gender  survived
male    0           468
female  1           233
male    1           109
female  0            81
Name: count, dtype: int64

14. find
    - average age of passengers who survived
    - average age of passengers who did not survived

In [77]:
print(df[df['survived']==1]['age'].mean())

28.343689655172415


In [78]:
print(df[df['survived']==0]['age'].mean())

30.62617924528302


15. convert age column into a numpy array and find
    - mean, std dev. , variance (ignore missing values)

In [79]:
arr=np.array(df[['age'])

In [87]:
print(np.nanmean(arr))

29.69911764705882


In [88]:
print(np.nanstd(arr))

14.516321150817316


In [89]:
print(np.nanvar(arr))

210.72357975366614


16. Using numpy create a new column called :
    - fare_with_tax
    - increased fare by 18%

In [92]:
fare_with_tax = np.array(df['fare']) + np.array(df['fare'])*0.18
fare_with_tax

array([  8.555   ,  84.114294,   9.3515  ,  62.658   ,   9.499   ,
         9.980794,  61.19775 ,  24.8685  ,  13.137294,  35.483544,
        19.706   ,  31.329   ,   9.499   ,  36.9045  ,   9.267956,
        18.88    ,  34.3675  ,  15.34    ,  21.24    ,   8.5255  ,
        30.68    ,  15.34    ,   9.474456,  41.89    ,  24.8685  ,
        37.03725 ,   8.5255  , 310.34    ,   9.297456,   9.317044,
        32.710544, 172.894544,   9.145   ,  12.39    ,  96.961544,
        61.36    ,   8.530456,   9.499   ,  21.24    ,  13.265206,
        11.1805  ,  24.78    ,   9.317044,  49.063456,   9.297456,
         9.499   ,  18.29    ,   9.145   ,  25.581456,  21.004   ,
        46.83125 ,   9.204   ,  90.540456,  30.68    ,  73.135456,
        41.89    ,  12.39    ,   8.530456,  32.745   ,  55.342   ,
         8.530456,  94.4     ,  98.5005  ,  32.922   ,  32.710544,
        17.990044,  12.39    ,   9.626794,   9.3515  ,  10.22175 ,
        12.39    ,  55.342   ,  86.73    ,  17.055956,  66.665

In [94]:
fare_with_tax=pd.Series(fare_with_tax)

In [96]:
df['fare_with_tax'] = fare_with_tax
df.head()

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck,fare_with_tax
0,0,3,male,22.0,1,0,7.2500,S,NaN,8.555000
1,1,1,female,38.0,1,0,71.2833,C,C,84.114294
2,1,3,female,26.0,0,0,7.9250,S,NaN,9.351500
3,1,1,female,35.0,1,0,53.1000,S,C,62.658000
4,0,3,male,35.0,0,0,8.0500,S,NaN,9.499000


18. create a numpy array from the fare column and :
     - replace all fares less than 10 with 10

In [97]:
fare_arr=np.array( df['fare']  )
fare_arr


array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0

In [98]:
fare_arr[fare_arr < 10] = 10
fare_arr

array([ 10.    ,  71.2833,  10.    ,  53.1   ,  10.    ,  10.    ,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        10.    ,  31.275 ,  10.    ,  16.    ,  29.125 ,  13.    ,
        18.    ,  10.    ,  26.    ,  13.    ,  10.    ,  35.5   ,
        21.075 ,  31.3875,  10.    , 263.    ,  10.    ,  10.    ,
        27.7208, 146.5208,  10.    ,  10.5   ,  82.1708,  52.    ,
        10.    ,  10.    ,  18.    ,  11.2417,  10.    ,  21.    ,
        10.    ,  41.5792,  10.    ,  10.    ,  15.5   ,  10.    ,
        21.6792,  17.8   ,  39.6875,  10.    ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,  10.    ,  27.75  ,  46.9   ,
        10.    ,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,  10.    ,  10.    ,  10.    ,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,  10.    ,  10.    ,  10.    ,
        29.    ,  12.475 ,  10.    ,  10.    ,  10.    ,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,  10.    , 263.    ,  10. 

19. create a new column called Age_Group:
    - Child : age<18
    - Adult :  10 to 60
    - Senior : age>60
      Then count passengers in each category

In [100]:
conditions=[
    df['age'] < 18,
    ( df['age'] >= 18) &  (df['age'] <= 60),
     df['age'] > 60
]
categories= ["Child","Adult","Senior"]
df["Age_Group"] = np.select (conditions,categories, default="Unknown")
print(df['Age_Group'].value_counts())

Age_Group
Adult      579
Unknown    177
Child      113
Senior      22
Name: count, dtype: int64


20. Find survival percentage for each passengers class

In [106]:
survival_per=df.groupby('pclass')['survived'].mean()*100
print(survival_per)

pclass
1    62.962963
2    47.282609
3    24.236253
Name: survived, dtype: float64


In [113]:
# formatting it
res = survival_per.reset_index()
res.columns=['Passenger Class','Survival Percentage']
print(res)

   Passenger Class  Survival Percentage
0                1            62.962963
1                2            47.282609
2                3            24.236253
